/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ISOMessageAPI */

#ifndef _Included_ISOMessageAPI
#define _Included_ISOMessageAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583APISetDebug
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ISOMessageAPI_ISO8583APISetDebug
  (JNIEnv *, jclass, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583APISetTrace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ISOMessageAPI_ISO8583APISetTrace
  (JNIEnv *, jclass, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583MessageCreate
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_ISOMessageAPI_ISO8583MessageCreate
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583MessageSetField
 * Signature: (IIILjava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_ISOMessageAPI_ISO8583MessageSetField
  (JNIEnv *, jclass, jint, jint, jint, jstring, jint, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583MessageSetFieldBinary
 * Signature: (III[BII)Z
 */
JNIEXPORT jboolean JNICALL Java_ISOMessageAPI_ISO8583MessageSetFieldBinary
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583MessageGetField
 * Signature: (IIIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ISOMessageAPI_ISO8583MessageGetField
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583MessageGetField2
 * Signature: (IIILjava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_ISOMessageAPI_ISO8583MessageGetField2
  (JNIEnv *, jclass, jint, jint, jint, jstring, jint, jint, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583MessageGetFieldBinary
 * Signature: (IIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ISOMessageAPI_ISO8583MessageGetFieldBinary
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583MessageGetFieldLength
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_ISOMessageAPI_ISO8583MessageGetFieldLength
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583MessageGetMessageType
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ISOMessageAPI_ISO8583MessageGetMessageType
  (JNIEnv *, jclass, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583MessageGetMapSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ISOMessageAPI_ISO8583MessageGetMapSize
  (JNIEnv *, jclass, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583MessageValidate
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_ISOMessageAPI_ISO8583MessageValidate
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583MessageGetResponseType
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ISOMessageAPI_ISO8583MessageGetResponseType
  (JNIEnv *, jclass, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583MessageSerialize
 * Signature: (III)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ISOMessageAPI_ISO8583MessageSerialize
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583MessageDeSerialize
 * Signature: (I[BII)Z
 */
JNIEXPORT jboolean JNICALL Java_ISOMessageAPI_ISO8583MessageDeSerialize
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583MessageDestroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ISOMessageAPI_ISO8583MessageDestroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583ConnectionCreate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ISOMessageAPI_ISO8583ConnectionCreate
  (JNIEnv *, jclass);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583ConnectionDestroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ISOMessageAPI_ISO8583ConnectionDestroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583ConnectionOpen
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_ISOMessageAPI_ISO8583ConnectionOpen
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jint, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583ConnectionClose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ISOMessageAPI_ISO8583ConnectionClose
  (JNIEnv *, jclass, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583ConnectionProcessMessage
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_ISOMessageAPI_ISO8583ConnectionProcessMessage
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583ConnectionAddMsgMapping
 * Signature: (ILjava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_ISOMessageAPI_ISO8583ConnectionAddMsgMapping
  (JNIEnv *, jclass, jint, jstring, jstring, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583ConnectionAwaitRequest
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ISOMessageAPI_ISO8583ConnectionAwaitRequest
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583ConnectionSendResponse
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_ISOMessageAPI_ISO8583ConnectionSendResponse
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISO8583ConnectionIsConnected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ISOMessageAPI_ISO8583ConnectionIsConnected
  (JNIEnv *, jclass, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISOStatusCreate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ISOMessageAPI_ISOStatusCreate
  (JNIEnv *, jclass);

/*
 * Class:     ISOMessageAPI
 * Method:    ISOStatusGetStatus
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ISOMessageAPI_ISOStatusGetStatus
  (JNIEnv *, jclass, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISOStatusGetResultCode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ISOMessageAPI_ISOStatusGetResultCode
  (JNIEnv *, jclass, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISOStatusGetResultDesc
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ISOMessageAPI_ISOStatusGetResultDesc
  (JNIEnv *, jclass, jint);

/*
 * Class:     ISOMessageAPI
 * Method:    ISOStatusDestroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ISOMessageAPI_ISOStatusDestroy
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif

