# $NetBSD: Makefile.common,v 1.13 2019/11/06 13:19:43 wiz Exp $
#
# used by textproc/libxml2/Makefile
# used by textproc/py-libxml2/Makefile

DISTNAME=	libxml2-2.9.13

EXTRACT_SUFX=	.tar.xz

CATEGORIES=	textproc
MASTER_SITES=   https://download.gnome.org/sources/libxml2/2.9/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://xmlsoft.org/

DISTINFO_FILE=	${.CURDIR}/../../textproc/libxml2/distinfo
PATCHDIR=	${.CURDIR}/../../textproc/libxml2/patches
